With part IV
kayleeisokay/csci-e106-final-project pull request #8
Opened 2023-12-04 03:29 UTC by thaylanabtoth

With part IV!

2023-12-04 04:03 UTC, kayleeisokay requested changes

2023-12-04 04:03 UTC, kayleeisokay commented on Class_Group_Project_Template.Rmd
> +```
Was there any marked improvement with the boxcox transformation? 

As a group in our last meeting we agreed that transforming the dependent variable isn't the right approach because it changes the interpretation of the coefficients  (percentage change instead of magnitude) and the specs told us to predict price. I understand one can transform the predictions back to original units but it isn't worth the complexity if the performance lift is low.

2023-12-04 04:03 UTC, kayleeisokay commented on Class_Group_Project_Template.Rmd
> +```
I believe the BP test doesn't test for normality. Anderson-Darling or Shapiro Wilks are tests that test for normality. BP test checks for hetereoskedasticity by seeing if there is a relationship between the errors and the values of the independent variables.

2023-12-04 04:03 UTC, kayleeisokay commented on Class_Group_Project_Template.Rmd
> +
For completeness sake can we add in bisquare weights? I suspect it'll do better since the data we're working with has a lot of outliers and influential points

2023-12-04 04:03 UTC, kayleeisokay commented on Class_Group_Project_Template.Rmd
> +
Lastly, can we add two tables at the end?

1. Table with all model coefficients where each row is a predictor variable and each column is a model. Refer to `Model_Data_Example_Bad_Data.Rmd` in the posit folder `TA Session Materials/`
2. Table with each model and associate test metric (e.g. adjusted rsquared, mae, mse).

2023-12-04 14:46 UTC, thaylanabtoth commented on Class_Group_Project_Template.Rmd
> +```
Yes, I wanted to discuss that. When I used the other code with a different way of handling the variables, it improved significantly. When I used the other one Flora sent, it got worse. So I want to check what's the difference in feature engineering that caused that. Moreover, it's not only performance, but assumptions were heavily violated without transformation, so there`s that to take into consideration as well

2023-12-04 14:47 UTC, thaylanabtoth commented on Class_Group_Project_Template.Rmd
> +```
You're correct. That's what happens when you work late at night :)

2023-12-04 14:49 UTC, thaylanabtoth commented on Class_Group_Project_Template.Rmd
> +
We could. I guess it would all depend on transformation again. When we log the price we don't have lots of outliers and influential points.

2023-12-04 18:34 UTC, kayleeisokay commented on Class_Group_Project_Template.Rmd
> +```
Which assumptions were violated? How did you check?

2023-12-04 18:35 UTC, kayleeisokay commented on Class_Group_Project_Template.Rmd
> +
I see. Log transformation moves points closer together so the effect of outliers is minimized.

2023-12-04 18:36 UTC, kayleeisokay commented
Summary of things blocking this MR

1. Table of results for model coefficients and model metrics
2. Revise Normality Test
3. Justification for using log transformation

2023-12-04 19:11 UTC, thaylanabtoth commented on Class_Group_Project_Template.Rmd
> +```
Through the plots.  
![image](https://github.com/kayleeisokay/csci-e106-final-project/assets/137568597/ef20a001-691c-469f-80c3-9a419105488c)
![image](https://github.com/kayleeisokay/csci-e106-final-project/assets/137568597/24a45e44-7638-41af-979e-47fcfef8050c)
![image](https://github.com/kayleeisokay/csci-e106-final-project/assets/137568597/4282d072-a1ad-4785-8833-87ac93f51428)

Here is the boxcox
![image](https://github.com/kayleeisokay/csci-e106-final-project/assets/137568597/b56672b1-954f-4283-895c-62cb7b0204c4)

Here are they after the log transformation
![image](https://github.com/kayleeisokay/csci-e106-final-project/assets/137568597/7d7a7c34-1ab8-4312-8e89-6fbe9214bab3)
![image](https://github.com/kayleeisokay/csci-e106-final-project/assets/137568597/9a1a8fd7-c04e-4294-8460-bbddae28da4e)
![image](https://github.com/kayleeisokay/csci-e106-final-project/assets/137568597/77cb3187-cfd4-40d6-88ad-3c982a2d4677)

2023-12-04 19:18 UTC, thaylanabtoth commented on Class_Group_Project_Template.Rmd
> +
Yep. And this kind of data is very good to be log-transformed. I was checking my other file (where I worked with different variables) and the baseline R2 was 0.74 (compared to 0.71 now) and after transformation and feature selection it went to 0.77 (compared to 0.68 in this file). Later I'll try to check the exact differences in the feature engineering, but this non official file definitely had a better performance. I don't know how to send it here, but I'll send an email to at least you and Flora to check it out. The difference is high, but maybe it's wrong. I think that would be the deciding factor between transformation or not.

2023-12-05 06:07 UTC, floralo40 commented on Class_Group_Project_Template.Rmd
> +```
The biggest difference in the variables in the new version is just that "month, "year", and "zipcode" were made into dummies in Part II. It's tricky because there's not really an alternative to making dummies for these variables.

Here's what I think: we don't have to worry too much about making the model perfect, but let's focus on demonstrating we made a reasonable effort at building a decent model and fixing any obvious problems. Therefore, can I propose the following to save time but also do a "good enough" job: 

1) @thaylanabtoth, when you said the model looked good using the original version, do you still have the R2 values? What was the highest R2 previously and what is the current R2? 

2) If it is a big difference in R2 (like >0.6), we can investigate further and maybe bring back parts of the old version. If the difference is less, I say it's not worth the effort of reverting to old model (and risk breaking something else), and we focus on remedial measures on the new model (transformations, weighted LS or robust regression). @kayleeisokay Like we discussed, I agree that boxcox is annoying and I'd only use it if it is significantly better than all other options (I mean, we could even do the boxcox transformation to show we thought about it, and explain that the small improvements wasn't worth sacrificing simplicity/ explainability of the model)

2023-12-05 06:11 UTC, floralo40 commented on Class_Group_Project_Template.Rmd
> +```
Actually I saw you mentioned the R2 in other comments below.

2023-12-11 21:26 UTC, closed without merging